### ISSUE TITLE
lesson 08: no interesting inputs found

### ISSUE THREAD

**Issue by juneJuly** [Dor1s/libfuzzer-workshop#1]
when i run xml_read_memory_fuzzer in lesson 08 , i got error like this:
'''
08$ ./xml_read_memory_fuzzer -max_total_time=300 -print_final_stats=1 corpus1
INFO: Seed: 1486712041
INFO: Loaded 0 modules (0 guards): 
Loading corpus dir: corpus1
INFO: -max_len is not provided, using 64
INFO: A corpus is not provided, starting from an empty corpus
#0	READ units: 1
#1	INITED exec/s: 0 rss: 31Mb
ERROR: no interesting inputs were found. Is the code instrumented for coverage? Exiting.
'''

did i missed something?
any suggestion?

**Comment by quangnh89** [comment]
I think you should change `FUZZ_CXXFLAGS` a little bit. Newest version of Clang supports `trace-pc-guard` flag. The compiler will insert instrumentation code on every edge. `8bit-counters` and `trace-pc-guard` can not combined together.
Try it:
```
export FUZZ_CXXFLAGS="-O2 -fno-omit-frame-pointer -g -fsanitize=address \
    -fsanitize-coverage=edge,trace-pc-guard,indirect-calls,trace-cmp,trace-div,trace-gep"
```

**Comment by juneJuly** [comment]
@quangnh89 
thank u very much ,  that works very well.
an u make everything very clear.

**Comment by Dor1s** [comment]
Thanks @quangnh89 !
