### ISSUE TITLE
run libfuzzer

### ISSUE THREAD

**Issue by zheng-yan-max** [Dor1s/libfuzzer-workshop#11]
Hello, the author, I encountered this problem when Implementing libfuzzer in MAC OS system:

Ld: file not found: / Applications/Xcode. The app/Contents/Developer/Toolchains/XcodeDefault xctoolchain/usr/lib/clang 12.0.0 / lib/Darwin/libclang_rt fuzzer_osx. A
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I wonder if you have any solution. Thank you very much

**Comment by Dor1s** [comment]
From the path it seems like you're using the LLVM package that is installed with Xcode. Apparently, that package doesn't have fuzzer runtime. You have the following options:

1) Download LLVM source code and build clang and compiler-rt yourself.
2) Download pre-built binaries from https://releases.llvm.org/download.html -- I've just checked, the fuzzer runtime is present in that build.
