### ISSUE TITLE
error in lesson4 

### ISSUE THREAD

**Issue by maru7777** [Dor1s/libfuzzer-workshop#14]
i used this instrcution below  to compile it : 
clang++ -g -std=c++11 -fsanitize=address -fsanitize-coverage=trace-pc-guard first_fuzzer.cc ../../libFuzzer/libFuzzer.a  -o first_fuzzer
then i runed
./first_fuzzer corpus1 
but it shows :
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer.
Please either migrate to a compiler that supports -fsanitize=fuzzer
or use an older version of libFuzzer
i use clang-7 clnag-9 cloang-10  to recompile but it is still show the following error. 
by the way , i download llvm bin file directly through github ,and setup env. so i didn't use your automatic build srcipt
could you please help me ?

**Comment by Dor1s** [comment]
Let me know if you have any more questions. Also please check out the disclaimer I've added to the README file: https://github.com/Dor1s/libfuzzer-workshop/commit/fffdea0ca1c8877250b1b4ec6b0f3e6f7a57aca2
