### ISSUE TITLE
Update libFuzzer version and revisit the lessons

### ISSUE THREAD

**Issue by Dor1s** [Dor1s/libfuzzer-workshop#5]
The workshop uses a hardcoded libFuzzer version which is pretty old these days. Would be nice to update it and check that the instructions are still applicable.

**Comment by zym-wade** [comment]
It would be nice if you could

**Comment by JulianVolodia** [comment]
> The workshop uses a hardcoded libFuzzer version which is pretty old these days. Would be nice to update it and check that the instructions are still applicable.

Hi @Dor1s ! Great repo and lessons learned here. Is there any viewable recording of workshops? Then, I maybe could follow and try do same things as in this repo (and, maybe fixing and leaving a changes for Your reviewiew instead of you fixing bc you could not have time maybe).

**Comment by Dor1s** [comment]
Thank you @JulianVolodia, unfortunately there is no recording available.

**Comment by JulianVolodia** [comment]
Thanks @Dor1s . Targeting Ubuntu 16.x or one of stable or tesing Debian will be enought? As I see fuzzing tools are quite alive and maybe you could share some tips. Maybe just should I review oss-fuzz for configurations used there?

**Comment by Dor1s** [comment]
Any image should work, just make sure to grab some fresh clang binaries or build it yourself.

**Comment by JulianVolodia** [comment]
@zym-wade sorry for no update. Must do some things before Thursday. Will keep you posted.

Good start is to check out llvm scripts, and build it (for example using this Dor1s script). https://raw.githubusercontent.com/Dor1s/libfuzzer-workshop/master/checkout_build_install_llvm.sh

Two things you need is Debian distro (I used one Debian like but Ubuntu also should work) and change `libgcc-5-dev` to `libgcc-10-dev`.

**Comment by JulianVolodia** [comment]
@zym-wade which distro you use, and what obstacles do you met?
Also, clusterfuzz runs on some LTS Ubuntus and Debian Jessie if I find out correctly here https://github.com/google/clusterfuzz/blob/master/local/install_deps_linux.bash 

Last but not least there is also another very valuable tutorial for libfuzzer I had have look: 
https://github.com/google/fuzzing/blob/master/tutorial/libFuzzerTutorial.md

**Comment by JulianVolodia** [comment]
My bad, indeed. Started to bring all examples to work with last libFuzzer as expected and fix READMEs' tutorial documentation too.

**Comment by JulianVolodia** [comment]
sorry for mess above - forgot about `#` is full of magic on Github.

**Comment by JulianVolodia** [comment]
Hmm.. just updated LLVM with libFuzzer to check if still all are good and some changes already done after my last update. :)
On 04/third_fuzzer will find crash without `-max_len=1024`, if using latest libFuzzer (not the one from `libFuzzer-update` branch update).
So, propose to any Reader of this message *not* to update libFuzzer until next review of workshop or diff outputs when something unexpected happens :)

```bash
./third_fuzzer c2
INFO: Seed: 3169287785
INFO: Loaded 1 modules   (39 inline 8-bit counters): 39 [0x7fb040, 0x7fb067), 
INFO: Loaded 1 PC tables (39 PCs): 39 [0x5b82f8,0x5b8568), 
INFO:        3 files found in c2
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 byt
es
INFO: seed corpus: files: 3 min: 8b max: 1026b total: 1042b rss: 26Mb
#4      INITED cov: 26 ft: 28 corp: 3/1042b exec/s: 0 rss: 27Mb
...
#315    REDUCE cov: 27 ft: 30 corp: 5/1044b lim: 1026 exec/s: 0 rss: 28Mb L: 1[76/1834]
 1 EraseBytes-
=================================================================
==8337==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd8dac4d28 at pc 
0x000000553ce2 bp 0x7ffd8dac4770 sp 0x7ffd8dac3f20
WRITE of size 1018 at 0x7ffd8dac4d28 thread T0
    #0 0x553ce1 in __asan_memmove /root/dor1s/libfuzzer-workshop/src/llvm/projects/comp
iler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:30
    #1 0x59ca78 in unsigned char* std::__copy_move<false, true, std::random_access_iter
ator_tag>::__copy_m<unsigned char>(unsigned char const*, unsigned char const*, unsigned
 char*) /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_algo
base.h:384:6
...
Address 0x7ffd8dac4d28 is located in stack of thread T0 at offset 1128 in frame
    #0 0x59bc2f in VulnerableFunction2(unsigned char const*, unsigned long, bool) /root
/dor1s/libfuzzer-workshop/lessons/04/./vulnerable_functions.h:42

  This frame has 3 object(s):
    [32, 64) 'header' (line 46)
    [96, 97) 'ref.tmp' (line 46)
    [112, 1128) 'body' (line 48) <== Memory access at offset 1128 overflows this variab
le
HINT: this may be a false positive if your program uses some custom stack unwind mechan
ism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /root/dor1s/libfuzzer-workshop/src/llv
m/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:30 in __asan_memmov
e
...
```

**Comment by JulianVolodia** [comment]
On lesson/08:
-dump_coverageee is deprecated for more than year.
Do you want
1) Clang Coverage like described here https://github.com/google/fuzzing/blob/master/tutorial/libFuzzerTutorial.md#visualizing-coverage,
2) use print_coverage and some tricks (to do things like in ealier versions), revert to earlier libFuzzer version, etc.
3) maybe you know some other solution which should be done?

**Comment by Dor1s** [comment]
Thanks a lot @JulianVolodia for working on this.

> My idea to add `-max_len=64` and show case this way.

Sure, sounds good.

For the coverage, I'd go with clang source based code coverage.

**Comment by JulianVolodia** [comment]
Good, will work with some clang libfuzzer thingy, because got stuck a while but hope I will go over with that. Dump feature was completely removed, and have only get coverage with older libFuzzer version and some tricks with gcc.

**Comment by JulianVolodia** [comment]
That's pleasure to work with on it. 😊 
Btw. If you want some boost on labs I prepared some multiprocessing edits for first python dumb fuzzing thingy right here: https://github.com/JulianVolodia/libfuzzer-workshop/commit/ac102f1d1f6106b4ab98819d25219dfa8cd32cc8 (branch https://github.com/JulianVolodia/libfuzzer-workshop/tree/python-mp-playground )
Previous work quite slow for me, on one thread, and that could be waste of time on labs if repeated.

**Comment by JulianVolodia** [comment]
Last but not least, if you have some TODOs on your list which I could work on that would be great for me to do it as exercise. I found some refs here: https://github.com/Dor1s/libfuzzer-workshop/pull/2

**Comment by Dor1s** [comment]
> Last but not least, if you have some TODOs on your list which I could work on that would be great for me to do it as exercise.

Sure, please go ahead, if you feel like :)

**Comment by JulianVolodia** [comment]
Ah sure, but is there anything you think is worth or planned doing? I have no access to your Todo's :D
Like, other things than in order to libFuzzer upgrade, inter alia mentioned refactor of last lessons to clang code cov?

**Comment by Dor1s** [comment]
My bad, I assumed you found some TODOs in the code / text. Nope, I don't think I have anything outside of this repo.

**Comment by JulianVolodia** [comment]
No problem, I just saying things enigmatic way last time. Sorry. I need at least week and will return because have some asap things. Best wishes and thanks for clarification!

**Comment by JulianVolodia** [comment]
That was long time. I will try to learn more about this sanitizer and clang because I think I lack of basic understanding how this all should work after changes (or use badly prepared version pallette of toolset).

I must understand Clang and current sanitizer better. Give me 2 weeks for getting this issue done. Thanks @Dor1s

**Comment by salmonx** [comment]
#13

**Comment by Dor1s** [comment]
Kind of addressed by https://github.com/Dor1s/libfuzzer-workshop/commit/fffdea0ca1c8877250b1b4ec6b0f3e6f7a57aca2
